---
# file: roles/openvpn_client/tasks/main.yml

## Install
- include: install-ubuntu.yml
  # when: ansible_distribution == 'Ubuntu'

# Configure client / server
- name: OpenVPN | Configure client
  include: configure-client.yml
  when: openvpn_config is defined and openvpn_type == 'client'
  tags: [openvpn_client_config]

## Configure service
- include: configure-upstart.yml

