# file: cloud-servers.yml
- hosts: cloud-servers
  roles:
    - role: openvpn_server
      openvpn_server: "{{openvpn_subnet}} {{openvpn_netmask}}"
      tag: openvpn_server
    - role: maxb.smokeping
      tag: smokeping
    - role: maxb.collectd
      collectd_plugins_custom: "{{
        collectd_plugins_snmp
      }}"
      collectd_plugins_snmp:
        - options:
          - LoadPlugin: snmp
      collectd_config_path: /etc/collectd/collectd.conf
      tag: collectd

