# file: debian-switches.yml
- hosts: debian-switches
  include: global-vars.yml
  roles:
    - role: switch
      tag: soekris_setup
    - role: openvpn_client
      tag: openvpn_client
    - role: bennojoy.network_interface
      tag: switch_network_setup
    - role: debops.snmpd
      snmpd_allow: [ "{{openvpn_subnet}}" ]
      tcpwrappers_deny_all: false
      tags: snmpd

