---
# file: roles/cloud_server/tasks/configure.yml

- name: Move easy-rsa files
  file: src=/usr/share/easy-rsa/ dest={{openvpn_etcdir}}/easy-rsa owner=root group=root state=link

- name: Clear any previous vars and keys
  file: path={{item}} state=absent
  with_items: 
    - openvpn_keydir
    - "{{openvpn_etcdir}}/vars"
    - "{{openvpn_etcdir}}/server.conf"
    - "{{openvpn_etcdir}}/build-server.sh"
    - "{{openvpn_etcdir}}/build-client.sh"
    - "{{openvpn_etcdir}}/revoke-client.sh"
  when: clear_vpn_server_config is defined and clear_vpn_server_config

- name: Generate scripts
  template: src={{item}}.j2 dest={{openvpn_etcdir}}/{{item}} mode=0700
  with_items: [vars, build-server.sh, build-client.sh, revoke-client.sh]

- name: Generate Server keys
  command: "{{openvpn_etcdir}}/build-server.sh"
  args: { creates: "{{ openvpn_keydir }}" }

- name: Generate Clients keys
  command: "{{openvpn_etcdir}}/build-client.sh {{item}}"
  args: { creates: "{{ openvpn_keydir }}/{{item}}.crt" }
  with_items: openvpn_clients

- name: Generate Clients configurations
  template: src=client.conf.j2 dest={{openvpn_keydir}}/{{item}}.conf
  with_items: openvpn_clients
  notify: openvpn pack clients
  register: openvpn_clients_changed

- name: Fetch client configs
  fetch: src={{openvpn_etcdir}}/keys/{{item}}.conf dest=roles/openvpn_client/files/ flat=yes
  with_items: openvpn_clients
  register: openvpn_client_confs_fetched

- name: Fetch client keys
  fetch: src={{openvpn_etcdir}}/keys/{{item}}.key dest=roles/openvpn_client/files/ flat=yes
  with_items: openvpn_clients
  register: openvpn_client_keys_fetched

- name: Fetch client certs
  fetch: src={{openvpn_etcdir}}/keys/{{item}}.crt dest=roles/openvpn_client/files/ flat=yes
  with_items: openvpn_clients
  register: openvpn_client_certs_fetched

- name: Fetch ca crt
  fetch: src={{openvpn_etcdir}}/keys/ca.crt dest=roles/openvpn_client/files/ flat=yes
  register: openvpn_ca_crt_fetched

- name: Setup PAM
  template: src=openvpn.pam.j2 dest=/etc/pam.d/openvpn
  when: openvpn_use_pam

- name: Configure users
  htpasswd: path={{openvpn_etcdir}}/users name={{item.name}} password={{item.password}} crypt_scheme=des_crypt
  with_items: openvpn_use_pam_users

- name: Setup LDAP
  template: src=auth-ldap.conf.j2 dest=/etc/openvpn/auth-ldap.conf
  when: openvpn_use_ldap

- name: Configure server
  template: src=server.conf.j2 dest={{openvpn_etcdir}}/server.conf
  notify: [openvpn restart]
