---
# file: roles/common/tasks/install_pilo.yml

  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - autoconf
      - automake1.11
      - build-essential
      - debhelper
      - fakeroot
      - libffi-dev
      - libssl-dev
      - libtool
      - bridge-utils
      - pkg-config
      - python-all
      - python-dev
      - python-pip
      - python-qt4
      - python-zopeinterface
      - python-twisted-conch
      - openvswitch-switch
      - python-openvswitch

  - name: install pox from github
    git: repo=https://github.com/denovogroup/pox.git
         dest={{pox_dir}}
         version=pilo

  - name: Set ip forwarding on
    sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

  - name: Copy PILO controller config
    template: src=pilo_controller.conf dest=/etc/default/pilo_controller.conf owner=root group=root mode=0644
    when: pilo_controller

  - name: Copy PILO client config
    template: src=pilo_client.conf dest=/etc/default/pilo_client.conf owner=root group=root mode=0644
    when: pilo_client 

  - name: Copy PILO controller init script
    template: src=pilo_controller dest=/etc/init.d/pilo_controller owner=root group=root mode=0744
    when: pilo_controller 

  - name: Copy PILO client init script
    template: src=pilo_client dest=/etc/init.d/pilo_client owner=root group=root mode=0744
    when: pilo_client 

  - name: Copy root files
    copy: src=root/ dest=/root/ owner=root group=root 
